---
title: "Combining Old and New dataset and Visualizing the data"
author: "KimYG"
date: "2022년 8월 12일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
Merged.DEG.HM <- bind_rows(DEG.HM.old, DEG.HM.New)
Merged.DEG.HM <- Merged.DEG.HM %>% distinct()

Old.Merged.stat <-  dt.stat.old %>% 
                  filter(`Mouse symbol` %in% Merged.DEG.HM$`Mouse symbol`) %>% 
                  select("Mouse symbol", "FC.HM", "log2FC.HM", "adjusted p-value.HM")
New.Merged.stat <-  dt.stat.new %>% 
                  filter(`Mouse symbol` %in% Merged.DEG.HM$`Mouse symbol`) %>% 
                  select("Mouse symbol", "FC.HM", "log2FC.HM", "adjusted p-value.HM")


Merged.DEG.HM.stat <- full_join(Old.Merged.stat, New.Merged.stat, by = "Mouse symbol", copy = FALSE, suffix = c(".old", ".new"), keep = FALSE, na_matches ="na")
colnames(Merged.DEG.HM.stat) <- c("Mouse symbol", "FC.old", "log2FC.old", "fdr.old", "FC.new", "log2FC.new", "fdr.new")
head(Merged.DEG.HM.stat)
```


```{r}
Merged.DEG.HM.stat <- Merged.DEG.HM.stat %>% 
                      mutate(log10.old = -log10(fdr.old), log10.new = -log10(fdr.new)) %>% 
                      mutate(in.new = `Mouse symbol` %in% DEG.HM.New$`Mouse symbol`) %>% 
                      mutate(in.old = `Mouse symbol` %in% DEG.HM.old$`Mouse symbol`) %>% 
                      mutate(common.elements = in.new + in.old) %>% 
                      mutate(grouping = case_when(
                        in.new == TRUE & in.old == TRUE ~ "both", 
                        in.new == TRUE & in.old == FALSE ~ "new",
                        in.new == FALSE & in.old == TRUE ~ "old"
                      )) %>%
                      mutate(significant.level.old = case_when(
                        log10.old >= 0 & log10.old < 1 ~ 0, 
                        log10.old >= 1 & log10.old < 1.30103 ~ 0.5,
                        log10.old >= 1.30103 & log10.old < 2 ~ 1,
                        TRUE ~ 1.5,
                      )) %>%
                      mutate(significant.level.new = case_when(
                        log10.new >= 0 & log10.new < 1 ~ 0, 
                        log10.new >= 1 & log10.new < 1.30103 ~ 0.5,
                        log10.new >= 1.30103 & log10.new < 2 ~ 1,
                        TRUE ~ 1.5,
                      )) %>%
                      mutate(labelforplot = case_when(
                        in.new == TRUE & in.old == TRUE ~ "both", 
                        in.new == TRUE & log10.old >= 1 & log10.old < 1.30103 ~ "new0",
                        in.new == TRUE & log10.old >= 0 & log10.old < 1 ~ "new1",
                        in.old == TRUE & log10.new >= 1 & log10.new < 1.30103 ~ "old0",
                        in.old == TRUE & log10.new >= 0 & log10.new < 1 ~ "old1"
                      )) %>%
                      arrange(grouping, labelforplot) %>% 
                      select(`Mouse symbol`, 
                             FC.old, 
                             log2FC.old, 
                             fdr.old, 
                             log10.old, 
                             significant.level.old,
                             FC.new, 
                             log2FC.new, 
                             fdr.new, 
                             log10.new,
                             significant.level.new,
                             grouping,
                             labelforplot) 
Merged.DEG.HM.stat$grouping <-factor(Merged.DEG.HM.stat$grouping, levels = c("both", "new", "old"))
Merged.DEG.HM.stat$labelforplot <-factor(Merged.DEG.HM.stat$labelforplot, levels = c("both", "new0", "old0", "new1", "old1"))
#write_tsv(Merged.DEG.HM.stat, 
#           file = paste(path.expand('~'),"/GitHub/R_script_for_data_analysis/RNA-Sequencing/Shank2/Merged.DEG.HM.stat.txt", sep = ""), 
#           na="NA"
#           )
Merged.DEG.HM.stat <- Merged.DEG.HM.stat %>% arrange(labelforplot, desc(log10.old))
head(Merged.DEG.HM.stat)
```

```{r}
#formatted.dt <- data.frame()

formatted.dt <- 
                  mutate(pivot_longer(Merged.DEG.HM.stat, cols = contains("log2FC."), 
                                      names_to = c("Variable", "Group"), 
                                      values_to = "log2FC", 
                                      names_sep = '\\.')) %>% 
                  mutate(pivot_longer(Merged.DEG.HM.stat, cols = contains("significant.level."),
                                      names_to = c("Variable2", "Group2"),
                                      values_to = "Significance.level", 
                                      names_sep = '\\.')) %>% 
                  select("Mouse symbol", "Group", "log2FC", "Significance.level") %>%   
                  filter(`Mouse symbol` != "Fam205a4")

formatted.dt$`Mouse symbol` <- factor(formatted.dt$`Mouse symbol`, levels = rev(Merged.DEG.HM.stat$`Mouse symbol`))
head(formatted.dt)
#write_tsv(formatted.dt, file = paste(path.expand('~'),"/GitHub/R_script_for_data_analysis/RNA-Sequencing/formatted_result.txt", sep = ""), na="NA")
```

```{r fig.width=3.5, fig.height=49}
#library(ggplot2)
breaks <- c(-2, -1, 0, 1, 2)
p <- ggplot(formatted.dt,aes(x=`Group`, y=`Mouse symbol`))+
  geom_point(aes(size=`Significance.level`,
                 color=`log2FC`))+
  scale_colour_gradient2(breaks = breaks,
                         low = "blue", 
                         mid = "white", 
                         high = "red", 
                         midpoint = 0, 
                         space = "Lab", 
                         na.value = "grey50", 
                         guide = "colourbar", 
                         aesthetics = "colour") +
  scale_size(labels = c("p >= 0.1 ","0.1 < p <= 0.05", "0.05 < p <= 0.01","p < 0.01")) +
  theme_dark() + 
  #scale_size(range = c(-2, 2)) + 
  labs(x=NULL,y=NULL) +
  guides(size=guide_legend(order=3))

p

ggsave("Bubble chart.png", width = 3.5, height = 49)
```


