---
title: "Grin2b KI ACC CaMKII-positive neuron excitability"
author: "KimYG"
date: "2022 Jan 27th"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 0. Load packages
```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(lme4)
library(nlme) #for generation of Linear Mixed Model
library(tidyverse) #for data manipulation and visualization
library(ggpubr) #for creating easily publication ready plots
library(rstatix) # provides pipe-friendly R functions for easy statistical analyses
library(lmerTest)
library(psycho)
library(Rmisc) # provides an easy way to Summerize data Mean, SD, SEM
library(emmeans) #for post hoc pairwise comparison of interaction in Mixed Effects Model)
library(ggplot2)
```
-------
## Analysis for depolarizing-current injection data 
### 1. Loading depolarizing-current injection data from Google drive and formatting the data
```{r, echo=FALSE}
table <- read.delim(file="I:/내 드라이브/CSBD life/2_Data/2022/Summary/WT/Depol.txt",
                   header=T,
                   sep='\t',
                   stringsAsFactors=T)
colnames(table) <- c("id", "Baseline","NOS", "MFR", "TD", "PBAHP", "AP_Onset", "Level")
table$Injected_current <- factor(table$Level,levels(table$Level), label= c(1:12)*50)
table$group  <- factor("WT")
head(table)
```
```{r, echo=FALSE}
table2 <- read.delim(file="I:/내 드라이브/CSBD life/2_Data/2022/Summary/KI/Depol.txt", 
                    header=T,
                    sep='\t',
                    stringsAsFactors=T)
colnames(table2) <- c("id", "Baseline","NOS", "MFR", "TD", "PBAHP", "AP_Onset", "Level" )
table2$Injected_current <- factor(table2$Level,levels(table2$Level), label= c(1:12)*50)
table2$group <- factor("KI")
head(table2)
```

```{r, results='hide', echo=FALSE}
Whole_data <- rbind(table, table2) ### 2. Combine two data-sets
str(Whole_data)
```

### 2. Discriptive statistics
```{r, results='hold', echo=FALSE}
Summary.df <- summarySE(Whole_data, measurevar = "NOS", groupvars = c("Injected_current", "group"), na.rm = T) #Summerize data Mean, SD, SEM 
print(Summary.df)
```

### 3. Prepare figure
```{r, echo=FALSE}
library(ggplot2)
ggplot(Summary.df, aes(x=Injected_current, y=NOS, colour=group, group=group)) + 
    geom_errorbar(aes(ymin=NOS-se, ymax=NOS+se), colour="black", width=.2) +
    geom_line() +
    geom_point(size=5, shape=21, fill="white") + # 21 is filled circle
    labs(x="Injected Current (pA)", y="Number of Spike", title="") + #Add axis titles
    scale_colour_hue(name= "",    # Legend label, use darker colors
                     breaks=c("WT", "KI"),
                     labels=c("WT", "KI"),
                     l=40) +                    # Use darker colors, lightness=40
    expand_limits(y=2) +                        # Expand y range
    scale_y_continuous(breaks=0:20*5) +         # Set tick every 2
    theme_classic(base_size = 11) +
    theme(legend.justification=c(1,0),
          legend.position="top",
          axis.text=element_text(size=10),
          axis.title=element_text(size=18, face="bold"))               # Position legend in bottom right

# boxplot(MFR ~ Protocol*Group, data = Data.df,
#        xlab = "Group", ylab = "Input Resistance",
#        frame = T, col = c("#00AFBB", "#E7B800", "#FC4E07"))
```


### 4. Generate LInear Mixed Model
```{r}
LMM.model <- lme(NOS ~ Injected_current*group, 
                 random = ~1|id, 
                 data=Whole_data, 
                 na.action = "na.omit")
```

### 5. Tests of Within- and Between-Subjects Effects 
```{r}
a <- aov(NOS~Injected_current+group+group*Injected_current+Error(id), data=Whole_data)
summary(a)
```
```{r}
anova(LMM.model)
```

### 6. Pairwise Comaprison 
```{r}
emm <- emmeans(LMM.model, ~ group|Injected_current)
post.hoc <- pairs(emm, adjust="tukey") #'tukey' is default, 'sidak', 'holm'
post.hoc
```
-----
## Analysis for AP paramenters
### 1.  Load depolarizing-current injection data from Google drive
```{r}
AP <- read.delim(file="I:/내 드라이브/CSBD life/2_Data/2022/Summary/WT/AP analysis.txt",
                   header=T,
                   sep='\t',
                   stringsAsFactors=T)
#colnames(table) <- c("id", "AP_Threshold","Velecity_at_threshold", "UpstrokeV", "DownstrokeV", "AP_Amplitude", "AHP_Amplitude", "FWHM", "Rin", "Rheobase_current", "Maximal_firing_step", "FI_slope", "Last_First_ISI")
AP$group  <- factor("WT")
AP2 <- read.delim(file="I:/내 드라이브/CSBD life/2_Data/2022/Summary/KI/AP analysis.txt",
                   header=T,
                   sep='\t',
                   stringsAsFactors=T)
AP2$group <- factor("KI")
Whole_AP <- rbind(AP, AP2) ### 2. Combine two data-sets
str(Whole_AP)
```

### 2. Discriptive statistics
```{r, results='hold'}
temp.data <- list()
for (n in 2:(length(colnames(Whole_AP))-1)) {
    temp.data[[colnames(Whole_AP)[n]]] <-summarySE(Whole_AP, measurevar = colnames(Whole_AP)[n], groupvars = "group", na.rm = T)
    colnames(temp.data[[n-1]]) <- c("Group","N", "mean", "SD", "SEM", "CI")
    }
Discriptive.AP <- as.data.frame(do.call(rbind, temp.data))
print(Discriptive.AP)
```

```{r}
t.result <- list()
for (n in 2:(length(colnames(Whole_AP))-1)) { 
  
  df1 <- filter(select(Whole_AP, colnames(Whole_AP)[n], group), group == "WT")
  colnames(df1) <- c("X", "Label")
  
  df2 <- filter(select(Whole_AP, colnames(Whole_AP)[n], group), group == "KI")
  colnames(df2) <- c("Y", "Label")
  
  var.result <- var.test(df1$X, df2$Y) #to evaluate the sample variences of the two groups. If p-value is greater than 0.05, then two variances are homogeneous.
  t.result[[colnames(Whole_AP)[n]]] <- if(var.result$p.value >= 0.05){
            t.test(df1$X, df2$Y, alternative = c("two.sided"), paired = F, var.equal = T)
             } else {
            t.test(df1$X, df2$Y, alternative = c("two.sided"), paired = F, var.equal = F)    
             }
  }

```

```{r}
p <- ggbarplot(Whole_AP, 
          x="group", 
          y="Rin",
          xlab="",
          ylab="Input resistance",
          ylim=c(0,200),
          width = 0.3,
          add = c("mean_se", "jitter"), 
          color="group",
          #palette=c("blue", "red"),
          position = position_dodge(0.5))
compare_means(Rin~group, data=Whole_AP, method="t.test")
p + stat_compare_means(aes(label = paste0("p = ", ..p.format..)))
```



      
      
